### ISSUE TITLE
Need to publish compiled apk in releases artifacts

### ISSUE THREAD

**Issue by inikoo** [inikoo/maya#15]
![Screenshot 2024-04-11 at 04 22 24](https://github.com/inikoo/maya/assets/8298090/65dd6d1f-514c-4c4d-ba0e-1cbda6984841)

**Comment by YudhistiraA** [comment]
![image](https://github.com/inikoo/maya/assets/42015612/74ca10d4-6c8d-48d6-ae0b-6e3b918aafb2)
