### ISSUE TITLE
Link of the builded app in repo artifacts section

### ISSUE THREAD

**Issue by inikoo** [inikoo/maya#6]
![Screenshot 2024-04-08 at 09 06 08](https://github.com/inikoo/maya/assets/8298090/7ea40e44-2296-44ba-a168-de69a44b4e9a)

**Comment by YudhistiraA** [comment]
i already create action artifact 

![image](https://github.com/inikoo/maya/assets/42015612/fcd70275-c0a0-46c6-8ebc-d0369d8df6e1)
